CREATE TABLE  coupon(
id UUID DEFAULT gen_random_uuid() PRIMARY_KEY,
city VARCHAR (100) NOT NULL,
uf VARCHAR (100) NOT NULL,
event_id UUID,
FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE CASCADE
);
